language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jonsom/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonsom/react-test yarn test --coverage

after_success:
  - docker build -t jonsom/multi-client ./client
  - docker build -t jonsom/multi-nginx ./nginx
  - docker build -t jonsom/multi-server ./server
  - docker build -t jonsom/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jonsom/multi-client
  - docker push jonsom/multi-nginx
  - docker push jonsom/multi-server
  - docker push jonsom/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucker_name: elasticbeanstalk-eu-west-3-176704227313
  bucket_path: docker-multi
  on:
   branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
